#+Title: My literate Syncthing settings
#+Author: Mark Armstrong
#+Description: A literate setup for Syncthing.

* Introduction

[[https://syncthing.net/][Syncthing]] is “a *continuous file synchonization* program”.
I use it as a “personal cloud storage” solution,
though it is not truly cloud storage;
everything is stored on my machines only.

I have found Syncthing very easy and intuitive to use,
and together with a backup solution on one of the synced machines,
it has perfectly replaced cloud storage solutions for me.

* Supervisor entry for auto-starting Syncthing

This file creates an entry for Syncthing with Supervisor,
for the purpose of automatically starting Syncthing on system boot.
Put a symbolic link tothe tangled
[[./conf/syncthing.conf]] in [[/etc/supervisor/conf.d/]].

Before tangling, set your username here.
The ~conf~ file below uses this entry for the user and user's home directory.
#+name: user
#+begin_src text
armkeh
#+end_src

And this is the actual ~conf~ file contents,
with the user's name entered using
[[https://orgmode.org/manual/Noweb-Reference-Syntax.html][Noweb reference syntax]].
#+begin_src conf :tangle ./conf/syncthing.conf :noweb tangle
[program:syncthing]
autorestart = True
directory = /home/<<user>>/
user = <<user>>
command = /usr/bin/syncthing -no-browser -home="/home/<<user>>/.config/syncthing"
environment = STNORESTART="1", HOME="/home/<<user>>"
#+end_src
