#+Title: My literate Emacs initialisation file
#+Description: My literate emacs initialisation file.
#+Startup: indent
#+Options: toc:1

* Introduction

This is my ~emacs~ initialisation code, documented for my own understanding
in the future and for sharing with others.

I'm following [[https://alhassy.github.io/init/][Musa's]] example using an ~org~ file for this.

** Setting up ~.emacs~ to use this code

Create a symbolic link to this file in =~/.emacs.d/~,
then add to the bottom of =~/.emacs= these lines:
#+BEGIN_EXAMPLE emacs-lisp
;; BEGIN my edits

;; I've set up an init file following Musa's guide: https://alhassy.github.io/init/

;; Enable Emacs VC on symlinked files
(setq vc-follow-symlinks t)

;; Evaluate my init file.
(org-babel-load-file "~/.emacs.d/emacs-init.org")

;; Byte compile the file so that changes to emacs-init.org get picked up.
(byte-compile-file "~/.emacs")

;; END my edits
#+END_EXAMPLE

*** Why set ~vc-follow-symlinks~ here?

It's a setting I want anyway (it ensures Emacs's version control
works correctly on the target file), but why set it in ~.emacs~?

Since ~.emacs~ uses a symlink to this version controlled file,
having Emacs prompt me every time is annoying and slows my start up.

* Major packages

** General

*** Add package repositories

 #+begin_src emacs-lisp
 (require 'package)
 (setq package-archives
    '(("melpa" . "https://melpa.org/packages/")
      ("gnu" . "https://elpa.gnu.org/packages/")
      ("org" . "http://orgmode.org/elpa/")))
 (package-initialize)
 #+end_src

*** COMMENT Set the load path for manually downloaded packages

(Currently I don't use manually downloaded packages)

 #+begin_src emacs-lisp
 (add-to-list 'load-path "~/Dropbox/Organisation/setup/emacs/downloaded-packages")
 #+end_src

** ~agda~ mode

We need Emacs to locate Agda mode. This command is put in ~.emacs~

#+begin_src emacs-lisp
(load-file (let ((coding-system-for-read 'utf-8))
                (shell-command-to-string "agda-mode locate")))
#+end_src

#+begin_src emacs-lisp
(require 'agda-input)
(require 'agda2-highlight)
#+end_src

*** Command line arguments

Dr. Wolfram Kahl has recommended the following settings.

(I'm not setting them right somehow...)

#+begin_src emacs-lisp
;;(setq agda2-program-args (quote ("RTS" "-M4G" "-H4G" "-A128M" "-RTS")))
#+end_src

These arguments specify
| ~+RTS~, ~-RTS~ | Flags between these are arguments to the ~ghc~ runtime |
| ~-M[size]~   | Maximum heap size                                    |
| ~-H[size]~   | Suggested heap size                                  |
| ~-A[size]~   | Allocation area size used by the garbage collector   |

Full documentation for the ~ghc~ runtime argumentscan be found [[https://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/runtime-control.html][here]].

Additional arguments that may be useful include
| ~-S[file]~ | Produces information about “each and every garbage collection” |
|          | - Outputs to ~stderr~ by default                               |

*** Alternative problem highlighting

I find the background coloring used by Agda for incomplete pattern matching,
redundant clauses and clauses which do not hold definitionally hard to read
in general, and usually unreadable with different themes.

So I use set other indicators instead.

#+begin_src emacs-lisp
(defun my-agda-highlighting ()
  "Set face attributes to replace Agda highlighting I find annoying."
  (set-face-attribute
    'agda2-highlight-coverage-problem-face
    nil ;; all frames
    :background nil
    :underline "dark red"
  )
  (set-face-attribute
    'agda2-highlight-reachability-problem-face
    nil ;; all frames
    :background nil
    :strike-through t
  )
  (set-face-attribute
    'agda2-highlight-catchall-clause-face
    nil ;; all frames
    :background nil
    :slant 'italic
  )
)

(add-hook 'agda2-mode-hook 'my-agda-highlighting)
#+end_src

*** Add unicode characters to Agda's translations

**** Punctuation and parentheses

#+begin_src emacs-lisp
(add-to-list 'agda-input-user-translations '(";;" "﹔"))
(add-to-list 'agda-input-user-translations '(";;" "⨾"))
(add-to-list 'agda-input-user-translations '("|" "❙"))
(add-to-list 'agda-input-user-translations '("st" "•"))
(add-to-list 'agda-input-user-translations '("{" "｛"))
(add-to-list 'agda-input-user-translations '("}" "｝"))
#+end_src

**** Activate the new additions

#+begin_src emacs-lisp
(agda-input-setup)
#+end_src

*** Activate Agda input mode in ~text~ and ~prog~ modes

#+begin_src emacs-lisp
(add-hook 'text-mode-hook
       (lambda () (set-input-method "Agda")))
(add-hook 'prog-mode-hook
       (lambda () (set-input-method "Agda")))
#+end_src

** ~org~ mode

#+begin_src emacs-lisp
(require 'org)
(require 'ox-extra)
#+end_src

*** Speed keys

Speed keys are single keystrokes which execute commands in an
~org~ file when the cursor is at the start of a headline.

#+begin_src emacs-lisp
(setq org-use-speed-commands t)
#+end_src

To see the commands available, execute
#+begin_example emacs-lisp
(org-speed-command-help)
#+end_example

*** Hide emphasis markers by default

#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src

*** COMMENT Template expansion (<s Tab, etc.)

 #+begin_src emacs-lisp
 (require 'org-tempo)
 #+end_src

**** Emacs Lisp source template: <el

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
     '("el" . "src emacs-lisp"))
#+end_src

**** (Org) Agda source template: <ag

#+begin_src emacs-lisp
(add-to-list 'org-structure-template-alist
     '("ag" . "src org-agda"))
#+end_src

**** Interactive Way to C source template: <ic

#+begin_src emacs-lisp
 (add-to-list 'org-structure-template-alist
      '("ic" . "src c :tangle (currently-working-with \"name\")"))
#+end_src

**** Interactive Way to C header template: <ich

#+begin_src emacs-lisp
 (add-to-list 'org-structure-template-alist
      '("ich" . "src c :tangle (currently-working-with-header \"name\")"))
#+end_src

**** Verbatim template: <ver

 #+begin_src emacs-lisp
 (add-to-list 'org-structure-template-alist
      '("ver" . "verbatim"))
 #+end_src

**** Answer template: <ans

 #+begin_src emacs-lisp
 (add-to-list 'org-structure-template-alist
      '("ans" . "answer"))
 #+end_src

*** Highlight math mode blocks

 #+begin_src emacs-lisp
 (setq org-highlight-latex-and-related '(latex))
 #+end_src

*** Exporting

**** Allow for ignoring headlines and/or subtrees

Use the ~:ignore:~ tag on headlines to omit the headline when
exporting, but keep its contents.

#+begin_src emacs-lisp
(ox-extras-activate '(ignore-headlines))
#+end_src

Alternatively, use the ~:noexport:~ tag to omit the headline
/and/ its contents.

#+begin_src emacs-lisp
;;;; noexport is in the list by default
;; (add-to-list 'org-export-exclude-tags "noexport")
#+end_src

**** Source code block indentation and colouring

I want to preserve my indentation for source code during export.
#+begin_src emacs-lisp
(setq org-src-preserve-indentation t)
#+end_src

The ~htmlize~ package preserves source code colouring on export to html.
(And presumably does a lot more I am not fully aware of).
#+begin_src emacs-lisp
(require 'htmlize)
#+end_src

**** Export in the background

Using ~latex-mk~, the export process takes a bit of time.
Tying up emacs during that time is annoying, so set the
export to happen in the background.

#+begin_src emacs-lisp
(setq org-export-in-background t)
#+end_src
**** LaTeX specific

***** Default LaTeX compiler

I use a lot of unicode, and I find ~xelatex~ and ~lualatex~
handle that more easily than ~pdflatex~.

From my experience so far, they seem pretty interchangable
for my purposes, so the decision of which to use is arbitrary.

Based on [[https://tex.stackexchange.com/questions/36/differences-between-luatex-context-and-xetex][this discussion on Stack Exchange]], LuaTeX seems the more
“up and coming” engine, so I'm using it at least until something breaks.

#+begin_src emacs-lisp
(setq org-latex-compiler "lualatex")
#+end_src

***** LaTeX compilation process

I use ~latexmk~ to automatically run as many passes as needed
to resolve references, etc.

#+begin_src emacs-lisp
(setq org-latex-pdf-process
      '("latexmk -%latex -f %f"))
#+end_src

The flags/format specifiers are
| ~%latex~        | stands in for the latex compiler (defaults to the setting above) |
| ~-f~            | force continued processing past errors                           |
| ~%f~            | stands in for the (relative) filename                            |

Other flags/format specifiers I may wish to add later include
| ~-shell-escape~ | necessary to use ~minted~ |

***** Custom document classes (customising outermost structure)

I want a ~report~ class that begins with ~chapter~'s, rather than
~part~'s.

#+begin_src emacs-lisp
(add-to-list
  'org-latex-classes
    '("report-noparts"
      "\\documentclass{report}"
      ("\\chapter{%s}" . "\\chapter*{%s}")
      ("\\section{%s}" . "\\section*{%s}")
      ("\\subsection{%s}" . "\\subsection*{%s}")
      ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
      ("\\paragraph{%s}" . "\\paragraph*{%s}")
      ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

***** Source code colouring in LaTeX exports

We can use ~minted~ for source code colouring on export to LaTeX.

Currently this breaks things with my literate Agda process,
a problem I should resolve. For the moment, if I want to use
~minted~, I can do so on a file-by-file basis.

⟪ ~pygments~ (also called ~python-pygments~) must be installed on the
  system for this to work. ⟫

#+begin_src emacs-lisp
;;(setq org-latex-listings 'minted
;;      org-latex-packages-alist '(("" "minted")))
#+end_src
*** Evaluating code

By default, Emacs will query whether we /actually/ want to
execute code when we evaluate a code block. Also, it seems to
just /not/ execute code marked for execution during export in an
~org~ file. So, I remove the safety.
#+begin_src emacs-lisp
(setq org-confirm-babel-evaluate nil)
#+end_src

Loading the following languages with ~require~ allows code blocks
in them to be evaluated.

By default only emacs lisp can be evaluated.

Documentation [[https://orgmode.org/manual/Languages.html][here]].

#+begin_src emacs-lisp
(require 'ob-C)
(require 'ob-haskell)
(require 'ob-latex)
(require 'ob-shell)
#+end_src

For shell code, we need to initialise via this function.
See [[https://emacs.stackexchange.com/questions/37692/how-to-fix-symbols-function-definition-is-void-org-babel-get-header][here]].
#+begin_src emacs-lisp
(org-babel-shell-initialize)
#+end_src

** ~pdf-tools~

Need to “install” it each time emacs starts
#+begin_src emacs-lisp
(pdf-tools-install)
#+end_src

*** COMMENT Default to midnight mode

#+begin_src emacs-lisp
(add-hook 'pdf-tools-enabled-hook 'pdf-view-midnight-minor-mode)
#+end_src

** ~yankpad~

#+begin_src emacs-lisp
(require 'yankpad)
(setq yankpad-file "~/Dropbox/Organisation/setup/emacs/yankpad.org")
#+end_src

I expand snippet keywords with ~C-c e~ (at least until yankpad
has smart tab expansion).
#+begin_src emacs-lisp
(global-set-key (kbd "C-c e") 'yankpad-expand)
#+end_src

Alternatively, ~C-c y m~ invokes ~yankpad-map~, which brings up a
keymap of the last tags of snippets.
#+begin_src emacs-lisp
(global-set-key (kbd "C-c y m") 'yankpad-map)
#+end_src

Changes to the yankpad file require ~yankpad-refresh~ to be run
to re-cache the snippets. For the moment, it seems like there is
separate caching for each buffer, meaning this command has to be
run in every buffer where I want changes to be picked up.
So, I have a shortcut key.
#+begin_src emacs-lisp
(global-set-key (kbd "C-c y r") 'yankpad-reload)
#+end_src

** ~yasnippet~

#+begin_src emacs-lisp
(require 'yasnippet)
;;(setq yas-snippet-dirs "~/Dropbox/Organisation/setup/emacs/snippets")
(yas-global-mode t)
#+end_src

~yas-wrap-around-region~ controls what is inserted for a snippet's
~$0~ field.

A non-nil, non-character setting has it insert the current region's
contents (i.e. if we highlight a region and invoke a snippet,
the region will be wrapped).

#+begin_src emacs-lisp
(setq yas-wrap-around-region t)
#+end_src

*** Don't add a final newline when editing snippet files

~yasnippets~ will insert the final newline when expanding a snippet,
so snippet files generally shouldn't include a final newline.

#+begin_src emacs-lisp
(add-hook 'snippet-mode-hook (setq require-final-newline nil))
#+end_src

*** Make ~org~ mode “play nice” with ~yasnippets~

#+begin_src emacs-lisp
(add-hook 'org-mode-hook
          (lambda ()
            (setq-local yas/trigger-key [tab])
            (define-key yas/keymap [tab] 'yas/next-field-or-maybe-expand)))
#+end_src

* Cosmetics

** Always confirm before closing Emacs

#+begin_src emacs-lisp
(setq confirm-kill-emacs 'yes-or-no-p)
#+end_src

** Remove unnecessary interface elements

Emacs usually shows a splash screen on startup,
which doesn't interest me.

#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
#+end_src

I don't use the tool bar (icons below the menu bar).

#+begin_src emacs-lisp
(tool-bar-mode ())
#+end_src

I also don't use the menu bar.

#+begin_src emacs-lisp
(menu-bar-mode ())
#+end_src

** Themes

I use the ~doom-nord~ themes,
and toggle between the non-~light~ and ~light~ variants.

#+begin_src emacs-lisp
(load-theme 'doom-nord t)

(setq my-dark-theme 'doom-nord)
(setq my-light-theme 'doom-nord-light)

(defun disable-all-custom-themes ()
  "Disable all custom themes.
   Returns the previous highest precendence theme
   (nil if no themes were previously enabled).

   Implementation:
     Gets the highest precedence applied theme as the first element
     of custom-enabled-themes.

     Then iteratively disables all the themes in custom-enabled-themes.
  "
  (let ((most-recent-theme (car custom-enabled-themes)))
    (while (car custom-enabled-themes)
      (disable-theme (car custom-enabled-themes)))
    most-recent-theme
  )
)

(defun toggle-my-themes ()
  "Disable all custom, then try to toggle the themes
   my-dark-theme and my-light-theme, in that if one was
   the last applied theme, the other will be applied.

   If neither was the last applied theme, my-dark-theme
   will be applied as a default.
  "

  (let ((most-recent-theme (disable-all-custom-themes)))
    (if (eq most-recent-theme my-dark-theme)
        (load-theme my-light-theme)
        (load-theme my-dark-theme)
    )
  )
)

(eq (car custom-enabled-themes) my-dark-theme)
(disable-all-custom-themes)
(toggle-my-themes)
#+end_src

Make it “play nice” with ~org~

#+begin_src emacs-lisp
(doom-themes-org-config)
#+end_src

** Information in the mode line

The doom themes package comes with a function to make
the mode line flash on error.
#+begin_src emacs-lisp
(doom-themes-visual-bell-config)
#+end_src

I'd previously just used ~visible-bell~, but it's a bit nosier
than necessary.
#+begin_src emacs-lisp
;;(setq visible-bell t)
#+end_src

I also like the mode line to show the data and time.
#+begin_src emacs-lisp
(setq display-time-day-and-date t)
(setq display-time-24h-format t)
(display-time)
#+end_src

It's also useful to see the line number and column number.
#+begin_src emacs-lisp
(line-number-mode t)
(column-number-mode t)
#+end_src
 
** Show line numbers on left (for ~text~ and ~prog~ mode)

#+begin_src emacs-lisp
(add-hook 'text-mode-hook 'linum-mode)
(add-hook 'prog-mode-hook 'linum-mode)
#+end_src

Setting it globally would conflict with ~pdf-tools~.
#+begin_src emacs-lisp
;; (global-linum-mode t)
#+end_src

** Highlight matching parenthesis when cursor is near

 #+begin_src emacs-lisp
 (load-library "paren")
 (show-paren-mode 1)
 (transient-mark-mode t)
 (require 'paren)
 #+end_src

** Show trailing whitespace

#+begin_src emacs-lisp
(custom-set-variables '(show-trailing-whitespace t))
#+end_src

** Display preferences for ~dired~

~dired~ makes use of switches for ~ls~.

I like the following switches:
| ~--group-directories-first~ | group directories before files                             |
| ~-a~                        | do not ignore entries starting with .                      |
| ~-B~                        | do not list implied entries ending with ~                  |
| ~-g~                        | long listing format, but do not list owner                 |
| ~-G~                        | in a long listing, don't print group names                 |
| ~-h~                        | print human readable size                                  |
| ~-L~                        | show information for /references/ rather than symbolic links |
|                           |                                                            |

-group-directories-first~   “group directories before files”
  - ~-a~ “do not ignore entries”

#+begin_src emacs-lisp
(setq dired-listing-switches "--group-directories-first -aBgGhL")
#+end_src

** Show ruler at 80 characters for (for ~text~ and ~prog~ mode)

#+begin_src emacs-lisp
(require 'fill-column-indicator)
(add-hook 'text-mode-hook 'fci-mode)
(add-hook 'prog-mode-hook 'fci-mode)
#+end_src

*** COMMENT Alternative code to activate it globally

From https://www.emacswiki.org/emacs/FillColumnIndicator

 #+begin_src emacs-lisp
 (require 'fill-column-indicator)
 (define-globalized-minor-mode global-fci-mode fci-mode (lambda () (fci-mode t)))
 (global-fci-mode t)
 #+end_src

** Wrap lines

#+begin_src emacs-lisp
(global-visual-line-mode t)
#+end_src

** TODO Use ~wordsmith~ for English syntax highlighting

#+begin_src emacs-lisp
(require 'wordsmith-mode)
#+end_src

** Use a single buffer for ~dired~

I use ~dired-single~ to avoid ~dired~ opening a new buffer
for every directory visited.

#+begin_src emacs-lisp
(require 'dired-single)
#+end_src

I use a “magic” buffer with the name ~*Dired*~, to avoid the single
~dired~ buffer being named after whatever directory I first visit.

#+begin_src emacs-lisp
(setq dired-single-use-magic-buffer t)
(setq dired-single-magic-buffer-name "*Dired*")
#+end_src

The below code, which rebinds keys to use ~dired-single~ rather than ~dired~,
is taken directly from the ~dired-single~ [[https://github.com/crocket/dired-single][GitHub readme]].

#+begin_src emacs-lisp
(defun my-dired-init ()
  "Bunch of stuff to run for dired, either immediately or when it's
   loaded."
  ;; <add other stuff here>
  (define-key dired-mode-map [return] 'dired-single-buffer)
  (define-key dired-mode-map [mouse-1] 'dired-single-buffer-mouse)
  (define-key dired-mode-map "^" 'dired-single-up-directory)
)

;; if dired's already loaded, then the keymap will be bound
(if (boundp 'dired-mode-map)
        ;; we're good to go; just add our bindings
        (my-dired-init)
  ;; it's not loaded yet, so add our bindings to the load-hook
  (add-hook 'dired-load-hook 'my-dired-init))
#+end_src

*** COMMENT Obsolete

I had manually downloaded this package previously.

#+begin_src emacs-lisp
(eval-after-load 'dired '(progn (require 'joseph-single-dired)))
#+end_src

** Buffers to open upon startup

*** Emacs init (this file)

#+begin_src emacs-lisp
(find-file "~/Dropbox/Organisation/setup/emacs/emacs-init.org")
#+end_src

*** Emacs tips and tricks

#+begin_src emacs-lisp
(find-file "~/Dropbox/Organisation/setup/emacs/tips-and-tricks.org")
#+end_src

*** Yasnippets file

#+begin_src emacs-lisp
(find-file "~/Dropbox/Organisation/setup/emacs/yasnippets.org")
#+end_src

*** My phone log

#+begin_src emacs-lisp
(find-file "~/Dropbox/Organisation/log/phone-log.org")
#+end_src

*** My log (as the initial buffer)

#+begin_src emacs-lisp
(setq initial-buffer-choice "~/Dropbox/Organisation/log/log.org")
#+end_src

* Shortcuts

** Textual insert shortcuts

*** “⋯”
#+begin_src emacs-lisp
(global-set-key (kbd "C-c d q")
                (lambda () (interactive) (insert "“”") (backward-char)))
#+end_src

*** ~\begin{⋯}~

#+begin_src emacs-lisp
(global-set-key (kbd "C-c l b e")
                (lambda () (interactive) (insert "\\begin{}") (backward-char)))
#+end_src

*** ~\end{⋯}~

#+begin_src emacs-lisp
(global-set-key (kbd "C-c l e e")
                (lambda () (interactive) (insert "\\end{}") (backward-char)))
#+end_src

*** ~\item_~

#+begin_src emacs-lisp
(global-set-key (kbd "C-c l i")
                (lambda () (interactive) (insert "\\item ")))
#+end_src

*** \begin{code} ⋯ \end{code}

*TODO*: I should make this accept an argument, or make a version that accepts an argument

*TODO*: (more ambitious) Make this take into account indentation.

#+begin_src emacs-lisp
(global-set-key (kbd "C-c l e c")
                (lambda () (interactive) (insert "\\begin{code}\n\n\\end{code}")
                                         (previous-line)))
#+end_src

** Emacs lisp commands

TODO: describe-symbol, describe-symbol-at-point, describe-key

** Org mode shortcuts
*** Moving subtrees

#+begin_src emacs-lisp
(global-set-key (kbd "C-c o s u")
                (lambda () (interactive) (org-move-subtree-up)))
(global-set-key (kbd "C-c o s d")
                (lambda () (interactive) (org-move-subtree-down)))
(global-set-key (kbd "C-c o s l")
                (lambda () (interactive) (org-promote-subtree)))
(global-set-key (kbd "C-c o s r")
                (lambda () (interactive) (org-demote-subtree)))
#+end_src

** ~dired~ shortcuts (C-c d _)

I use commands starting in ~C-c d~ to quickly navigate to directories
using ~dired~.

#+begin_src emacs-lisp
(setq my-dired-shortcut-prefix "C-c d")
#+end_src

All my files live in my Dropbox, so this prefix is useful.

#+begin_src emacs-lisp
(setq my-dired-shortcut-path-prefix "~/Dropbox/")
#+end_src

As seen in ~Cosmetics~, I use ~dired-single~ in order to only have one
~dired~ buffer at a time. In case this changes, I define another
local variable to store the command to invoke ~dired~ with.

#+begin_src emacs-lisp
(defun my-dired-invocation (directory) (dired-single-magic-buffer directory))
#+end_src

*** Home ~h~

#+begin_src emacs-lisp
(global-set-key (kbd (concat my-dired-shortcut-prefix "h"))
                (lambda () (interactive) (my-dired-invocation "~")))
#+end_src

*** Dropbox ~d~

#+begin_src emacs-lisp
(global-set-key (kbd (concat my-dired-shortcut-prefix "d"))
                (lambda () (interactive) (my-dired-invocation "~/Dropbox")))
#+end_src

*** Organisation ~o~

#+begin_src emacs-lisp
(global-set-key (kbd (concat my-dired-shortcut-prefix "o"))
                (lambda () (interactive) (my-dired-invocation (concat my-dired-shortcut-path-prefix "Organisation"))))
#+end_src

*** McMaster ~m~

#+begin_src emacs-lisp
(global-set-key (kbd (concat my-dired-shortcut-prefix "m"))
                (lambda () (interactive) (my-dired-invocation "~/Dropbox/McMaster/")))
#+end_src

*** Thesis ~t~

#+begin_src emacs-lisp
(global-set-key (kbd (concat my-dired-shortcut-prefix "t"))
                (lambda () (interactive) (my-dired-invocation "~/Dropbox/McMaster/Agda/thesis")))
#+end_src

*** Courses ~c~

**** 3ea3 ~e~

#+begin_src emacs-lisp
(global-set-key (kbd (concat my-dired-shortcut-prefix "c e"))
                (lambda () (interactive) (my-dired-invocation "~/Dropbox/McMaster/3ea3")))
#+end_src

** ~magit~ shortcuts

#+begin_src emacs-lisp
(global-set-key (kbd "C-c g")
                'magit-status)
#+end_src

** General

*** Dad jokes

I love the package ~dad-joke~.

#+begin_src emacs-lisp
(global-set-key (kbd "C-c d j")
                '(lambda () (interactive)
                         (dad-joke)))
#+end_src

*** Go to top/bottom of buffer (~M-<~, ~M->~ replacements)

#+begin_src emacs-lisp
(global-set-key (kbd "C-c b t")
                '(lambda () (interactive)
                         (beginning-of-buffer)))

(global-set-key (kbd "C-c b b")
                '(lambda () (interactive)
                         (end-of-buffer)))
#+end_src

*** ~F5~ to reload buffer

#+begin_src emacs-lisp
(global-set-key [f5]
                '(lambda () (interactive)
                         (revert-buffer nil t nil)))
#+end_src

*** Toggle my themes ~C-c t t~

#+begin_src emacs-lisp
(global-set-key (kbd "C-c t t")
                '(lambda () (interactive)
                 (toggle-my-themes)))
#+end_src

*** Disable all custom themes ~C-c t c~

#+begin_src emacs-lisp
(global-set-key (kbd "C-c t c")
                '(lambda () (interactive)
                 (disable-all-custom-themes)))
#+end_src

* Other

** Run my custom “dropbox start” command to ensure dropbox is running on the system

#+begin_src emacs-lisp
(start-process-shell-command "dropbox-start"
                             "*dropbox-start*"
                             "/opt/dropbox-filesystem-fix/dropbox_start.py")
#+end_src

* Scratch
